don't use compact formatter
this formatter is causing errors with latest commander

➔ badev --help
(erb):2:in `get_binding': undefined method `size' for nil:NilClass (NoMethodError)
        from /Users/darwin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/erb.rb:863:in `eval'
        from /Users/darwin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/erb.rb:863:in `result'
        from /Users/darwin/.rvm/gems/ruby-2.2.1/gems/commander-4.3.3/lib/commander/help_formatters/terminal.rb:7:in `render'
        from /Users/darwin/.rvm/gems/ruby-2.2.1/gems/commander-4.3.3/lib/commander/runner.rb:302:in `block (2 levels) in create_default_commands'
        from /Users/darwin/.rvm/gems/ruby-2.2.1/gems/commander-4.3.3/lib/commander/command.rb:178:in `call'
        from /Users/darwin/.rvm/gems/ruby-2.2.1/gems/commander-4.3.3/lib/commander/command.rb:178:in `call'
        from /Users/darwin/.rvm/gems/ruby-2.2.1/gems/commander-4.3.3/lib/commander/command.rb:153:in `run'
        from /Users/darwin/.rvm/gems/ruby-2.2.1/gems/commander-4.3.3/lib/commander/runner.rb:57:in `block in run!'
        from /Users/darwin/.rvm/gems/ruby-2.2.1/gems/commander-4.3.3/lib/commander/runner.rb:382:in `block in global_option_proc'
        from /Users/darwin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/optparse.rb:1396:in `call'
        from /Users/darwin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/optparse.rb:1396:in `block in parse_in_order'
        from /Users/darwin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/optparse.rb:1383:in `catch'
        from /Users/darwin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/optparse.rb:1383:in `parse_in_order'
        from /Users/darwin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/optparse.rb:1377:in `order!'
        from /Users/darwin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/optparse.rb:1469:in `permute!'
        from /Users/darwin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/optparse.rb:1491:in `parse!'
        from /Users/darwin/.rvm/gems/ruby-2.2.1/gems/commander-4.3.3/lib/commander/runner.rb:363:in `parse_global_options'
        from /Users/darwin/.rvm/gems/ruby-2.2.1/gems/commander-4.3.3/lib/commander/runner.rb:65:in `run!'
        from /Users/darwin/.rvm/gems/ruby-2.2.1/gems/commander-4.3.3/lib/commander/delegates.rb:15:in `run!'
        from /Users/darwin/.rvm/gems/ruby-2.2.1/gems/commander-4.3.3/lib/commander/import.rb:8:in `block in <top (required)>'